services:

  Apps.controllers.ProductGetItemController:
    class: ../../controllers/ProductGetItemController
    arguments: ["@Contexts.products.application.ProductManager"]

  Apps.controllers.ProductListItemsController:
    class: ../../controllers/ProductListItemsController
    arguments: [ "@Contexts.products.application.ProductManager" ]

  Contexts.products.application.ProductManager:
    class: ../../../contexts/products/application/ProductManager
    arguments: ["@Contexts.products.infrastructure.ProductRepository"]

  Contexts.products.infrastructure.ProductRepository:
    class: ../../../contexts/products/infrastructure/ProductRepository
    arguments: [""]
